apiVersion: apps/v1
kind: Deployment
metadata:
  name: anthra-api
  labels:
    app: anthra-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anthra-api
  template:
    metadata:
      labels:
        app: anthra-api
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: api
          image: anthra-api:seclab
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: DB_HOST
              value: anthra-db
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: anthra
            - name: DB_USER
              value: anthra
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: anthra-db-secret
                  key: password
            - name: CORS_ORIGINS
              value: "http://localhost:30000,http://localhost:8080"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            readOnlyRootFilesystem: true
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
