apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: anthra

resources:
  - namespace.yaml
  - deployment-db.yaml
  - deployment-api.yaml
  - deployment-ui.yaml
  - deployment-log-ingest.yaml
  - services.yaml

commonLabels:
  managed-by: kustomize
  project: anthra-seclab
