server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location /api {
        resolver kube-dns.kube-system.svc.cluster.local valid=10s;
        set $upstream anthra-api.anthra.svc.cluster.local;
        proxy_pass http://$upstream:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
